/**
 * cv-library.mjs — named base CVs, layered on top of the single cv.md every
 * other part of career-ops (every mode, every script, every CLI) already
 * assumes exists at the tenant root.
 *
 * The rest of the system is CLI-agnostic and reads `cv.md` directly — dozens
 * of `.mjs` scripts and mode prompts, not just this web app. Reworking all of
 * that to accept "which CV" as a parameter would be an enormous, high-risk
 * change for a web-only feature. Instead, multi-CV is a layer ON TOP: a user
 * can keep several named CVs (`cvs/{id}.md`, e.g. "Backend", "AI/ML"), and
 * whichever one is ACTIVE is kept mirrored into `cv.md` — so the invariant
 * "cv.md == the active CV's content" always holds, and every existing mode,
 * script and report keeps working completely unmodified.
 *
 * Storage, per tenant root:
 *   cvs/index.json   — { activeId, cvs: [{id, name, createdAt, updatedAt}] }
 *   cvs/{id}.md       — that CV's content
 *   cv.md             — mirror of the active CV's content (untouched by this
 *                       module's readers; only writers sync it)
 *
 * Lazy, non-destructive migration: an account that predates this feature has
 * `cv.md` but no `cvs/` directory. The FIRST call into this module for that
 * tenant seeds `cvs/default.md` from the existing `cv.md` (zero data loss,
 * zero disruption) and marks it active. An account with NEITHER file yet gets
 * an empty index that is not persisted to disk until a real write happens —
 * so a fresh signup's tenant directory doesn't sprout a stray `cvs/` folder
 * before the user ever adds a CV.
 *
 * Plain .mjs (same pattern as pdf-paths.mjs / cv-envelope.mjs) so this can be
 * unit-tested with `node --test`, no TypeScript build step, and `root` is
 * always a parameter rather than resolved internally — this module has no
 * opinion on which tenant it's operating on.
 */
import fs from "node:fs";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { slugify } from "./pdf-paths.mjs";

const MAX_NAME_LEN = 80;
const MAX_CV_BYTES = 200_000; // matches /api/cv's existing ceiling

function cvsDir(root) {
  return path.join(root, "cvs");
}

function indexPath(root) {
  return path.join(cvsDir(root), "index.json");
}

function cvMdPath(root) {
  return path.join(root, "cv.md");
}

/** Every real id is generated by this module — never trust one from a URL param without checking this first (path-traversal guard). */
export function isValidCvId(id) {
  return typeof id === "string" && /^[a-z0-9](?:[a-z0-9-]{0,62}[a-z0-9])?$/.test(id);
}

function cvFilePath(root, id) {
  if (!isValidCvId(id)) throw new Error(`cv-library: not a valid CV id: ${JSON.stringify(id)}`);
  return path.join(cvsDir(root), `${id}.md`);
}

function atomicWrite(file, content) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  const tmp = `${file}.tmp-${process.pid}-${randomUUID()}`;
  fs.writeFileSync(tmp, content, "utf8");
  fs.renameSync(tmp, file);
}

/** Snapshot a file's current content to a timestamped .bak before overwriting, mirroring web/src/lib/core/safe-write.ts's convention (kept separate here so this module stays free of TypeScript dependencies — see the file header). */
function backup(file) {
  try {
    const cur = fs.readFileSync(file, "utf8");
    if (!cur.trim()) return null;
    const ts = new Date().toISOString().replace(/[:.]/g, "-");
    const bak = `${file}.bak-${ts}`;
    fs.writeFileSync(bak, cur, "utf8");
    return bak;
  } catch {
    return null;
  }
}

function readLegacyCv(root) {
  try {
    return fs.readFileSync(cvMdPath(root), "utf8");
  } catch {
    return null;
  }
}

/**
 * The index as it exists on disk RIGHT NOW, with no migration side-effect.
 * Used where creating cvs/ as a side effect of a read would be wrong (e.g.
 * cv-history.mjs, which should only mention a named CV when the feature is
 * actually in use).
 * @returns {{activeId: string|null, cvs: object[]}|null} null when cvs/index.json does not exist yet.
 */
export function peekIndex(root) {
  try {
    const raw = fs.readFileSync(indexPath(root), "utf8");
    const parsed = JSON.parse(raw);
    if (!parsed || !Array.isArray(parsed.cvs)) return null;
    return { activeId: parsed.activeId ?? null, cvs: parsed.cvs };
  } catch {
    return null;
  }
}

/**
 * The index, migrating from a legacy cv.md the first time this is called for
 * a tenant that has one, and persisting that migration so it only ever runs
 * once. Never persists an empty index — a brand-new tenant with neither
 * cvs/ nor cv.md gets `{activeId: null, cvs: []}` back in memory only.
 */
function ensureIndex(root) {
  const existing = peekIndex(root);
  if (existing) return existing;

  const legacy = readLegacyCv(root);
  if (legacy === null) return { activeId: null, cvs: [] };

  const now = new Date().toISOString();
  const seeded = { activeId: "default", cvs: [{ id: "default", name: "Default", createdAt: now, updatedAt: now }] };
  atomicWrite(cvFilePath(root, "default"), legacy);
  writeIndex(root, seeded);
  return seeded;
}

function writeIndex(root, index) {
  atomicWrite(indexPath(root), JSON.stringify(index, null, 2));
}

function validateName(name) {
  const trimmed = String(name ?? "").trim();
  if (!trimmed) throw new Error("cv-library: name is required");
  if (trimmed.length > MAX_NAME_LEN) throw new Error(`cv-library: name must be ${MAX_NAME_LEN} characters or fewer`);
  return trimmed;
}

function validateContent(content) {
  const c = typeof content === "string" ? content : "";
  if (Buffer.byteLength(c, "utf8") > MAX_CV_BYTES) throw new Error("cv-library: CV is too large (over 200KB)");
  return c;
}

// "history" is a static sibling route (/api/cvs/history, GET-only, lists the
// tailored-CV log) next to the dynamic /api/cvs/[cvId] routes. Next.js
// resolves the static segment first, so a CV that happened to land on this
// exact id would be permanently unreachable through its own GET/PUT/DELETE —
// treated as pre-taken here so uniqueId() always suffixes it instead.
const RESERVED_IDS = new Set(["history"]);

/** Unique id derived from `name`, appending -2/-3/... on collision OR a reserved id (stable ids: renaming a CV never changes its id or filename). */
function uniqueId(existingIds, name) {
  const base = slugify(name) || "cv";
  if (!existingIds.has(base) && !RESERVED_IDS.has(base)) return base;
  for (let n = 2; ; n++) {
    const candidate = `${base}-${n}`;
    if (!existingIds.has(candidate) && !RESERVED_IDS.has(candidate)) return candidate;
  }
}

/** List every named CV for this tenant (metadata only — no content, for a cheap switcher UI). Triggers the legacy-cv.md migration on first call. */
export function listCvs(root) {
  const idx = ensureIndex(root);
  return { activeId: idx.activeId, cvs: idx.cvs.map((c) => ({ ...c, active: c.id === idx.activeId })) };
}

/** One CV's full content, or null if `id` doesn't exist. */
export function getCv(root, id) {
  const idx = ensureIndex(root);
  const meta = idx.cvs.find((c) => c.id === id);
  if (!meta) return null;
  let content = "";
  try {
    content = fs.readFileSync(cvFilePath(root, id), "utf8");
  } catch {
    // The index and the file disagreeing is a bug, not a reason to 500 — an
    // empty CV is at least honestly editable and re-saveable.
  }
  return { ...meta, content, active: idx.activeId === id };
}

/**
 * Create a new named CV. The very first CV a tenant ever creates is
 * automatically activated (mirrored into cv.md) — there is no meaningful
 * "inactive" state when it is the only one that exists.
 */
export function createCv(root, { name, content = "" }) {
  const cleanName = validateName(name);
  const cleanContent = validateContent(content);
  const idx = ensureIndex(root);
  const id = uniqueId(new Set(idx.cvs.map((c) => c.id)), cleanName);
  const now = new Date().toISOString();

  atomicWrite(cvFilePath(root, id), cleanContent);
  const record = { id, name: cleanName, createdAt: now, updatedAt: now };
  idx.cvs.push(record);
  const isFirst = idx.cvs.length === 1;
  if (isFirst) {
    idx.activeId = id;
    backup(cvMdPath(root));
    atomicWrite(cvMdPath(root), cleanContent);
  }
  writeIndex(root, idx);
  return { ...record, active: isFirst };
}

/** Overwrite a CV's content. If it is the active one, cv.md is kept in sync in the same call — the invariant every other mode/script relies on. */
export function updateCv(root, id, content) {
  const cleanContent = validateContent(content);
  const idx = ensureIndex(root);
  const meta = idx.cvs.find((c) => c.id === id);
  if (!meta) return null;

  atomicWrite(cvFilePath(root, id), cleanContent);
  meta.updatedAt = new Date().toISOString();
  let backedUp = null;
  if (idx.activeId === id) {
    backedUp = backup(cvMdPath(root));
    atomicWrite(cvMdPath(root), cleanContent);
  }
  writeIndex(root, idx);
  return { ...meta, content: cleanContent, active: idx.activeId === id, backedUp: !!backedUp };
}

/** Rename a CV. Its id (and filename) never changes — only the id is stable enough to be worth guaranteeing to callers that stored it. */
export function renameCv(root, id, name) {
  const cleanName = validateName(name);
  const idx = ensureIndex(root);
  const meta = idx.cvs.find((c) => c.id === id);
  if (!meta) return null;
  meta.name = cleanName;
  meta.updatedAt = new Date().toISOString();
  writeIndex(root, idx);
  return { ...meta, active: idx.activeId === id };
}

/**
 * Delete a CV. Refuses to delete the active one — cv.md always has to keep
 * meaning something, and silently picking a replacement active CV on
 * deletion would change cv.md (and therefore what every mode/report reads)
 * as a side effect of a delete, which is a surprising place for that to
 * happen. Activate a different CV first, then delete the one that used to be
 * active.
 */
export function deleteCv(root, id) {
  const idx = ensureIndex(root);
  const i = idx.cvs.findIndex((c) => c.id === id);
  if (i === -1) return { ok: false, error: "not-found" };
  if (idx.activeId === id) return { ok: false, error: "is-active" };
  idx.cvs.splice(i, 1);
  writeIndex(root, idx);
  try {
    fs.rmSync(cvFilePath(root, id), { force: true });
  } catch {
    /* best-effort — the index no longer references it either way */
  }
  return { ok: true };
}

/** Make `id` the active CV, mirroring its content into cv.md so every existing mode/script/report keeps reading the CV the user actually selected. */
export function activateCv(root, id) {
  const idx = ensureIndex(root);
  const meta = idx.cvs.find((c) => c.id === id);
  if (!meta) return { ok: false, error: "not-found" };
  if (idx.activeId === id) return { ok: true, alreadyActive: true };

  let content = "";
  try {
    content = fs.readFileSync(cvFilePath(root, id), "utf8");
  } catch {
    /* an empty/missing file still activates — nothing here throws on a data-consistency gap */
  }
  const backedUp = backup(cvMdPath(root));
  atomicWrite(cvMdPath(root), content);
  idx.activeId = id;
  writeIndex(root, idx);
  return { ok: true, alreadyActive: false, backedUp: !!backedUp };
}

/**
 * The active CV's id and display name, WITHOUT triggering the legacy
 * migration — for callers (cv-history.mjs) that should only attribute a
 * tailored CV to a named base CV when the multi-CV feature is actually in
 * use, never as a side effect of merely checking.
 * @returns {{id: string, name: string}|null}
 */
export function peekActiveCv(root) {
  const idx = peekIndex(root);
  if (!idx || !idx.activeId) return null;
  const meta = idx.cvs.find((c) => c.id === idx.activeId);
  return meta ? { id: meta.id, name: meta.name } : null;
}
